server:
  port: 8081

spring:
  application:
    name: frame

  datasource:
    name: test
    url: jdbc:mysql://47.101.151.43:3306/frame
    username: root
    password: 12345
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
      host: localhost
      password:
      port: 6379
      lettuce:
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: top.zhouy.frameboot.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

alipay:
  appID: 2016092900626977
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzHZvVl5GkwtdJfH8cuXz5vC52Du0TFBu1BQMOkeTLKP01vQBSD5tKPQM8G/XByHwJbA9wUmMrcjPFlr4d9I2CGZ0aR3WviM0o2HBdxaeqyEC8RZ5MarI9SoBvGzp1GcZU8V3B79h/w2yDl0KTFZPB4qQXMFCgQaPckCwKDeQDKVw4YEWCEtpgd+giGWvt6XoDFCFq6Saq/PnVEm55JfxLcnY6vKpZo/os0YZinp9TN3yO7HG5hJGCQZRUzuIBYX+7WLHA5BgRlikMHUipGSE2k6s7y/zQl409aPQ50wFj0PjTKrzf1x0Wdg1g0Js29HWy+VduBiJcclLOGmS6qGqBAgMBAAECggEAWJpF8xOmHS2w1445RtlOxC7dgNMDXVOuHQ6co4Fx/zmIgCO9W9qSg9fImNxv5mspSHPm8zYeDmjQyWY3J5RIx9mpyE0fHzT538GpXAmhVi73Lur1UnHZN8551/xNH44fePdo3L2riBAAxtt1OFMNI3TcnQfuakfuKfY7gsG6UAE5736yZJj5L2cXrVl27zGqift9DluTDZBlUUHa7sXxQX00GVpkvHe2BD6ERYt9gZV+MQbkO4zZ2j0b3ZEV2NavW9c8T2Ho/TF8Vn/wUUfxFtdvpxQ3cERsqoLgBhysBUhkhniwAhDzgCT7q8zTanhQH4mFC7mFP/euYcn9j4/dAQKBgQDrKgQAWs03sxjxA9Bv81bZR4OCUw/PWmwtgl89KU1v14OhukXxSOOdN0+Pjgfwj0D1sPTYsqiqq3KGYaEgh9O2w8hD/zA7fDaSHcZagHcNL0SXp9FYvEM7FN33hI9eE+YWsrD2WGW2izJftCc82pAoyFT3mNmWuMo6ynv9y0a4UQKBgQDC/E3F2ZUTttItFo2ejINXltZtWIRm5sl9IXifPE2DTiDVqoZrsA3RLHa9MU/54JykPQKSbfzsEOF38tbt6Nw0Y2dFO/rRTmstds52b8OAa0aXdIUgovmGvAYFGCfhXTJDITtpiGAGB+yaoSsJelyOnhRV77O+UNp2prZXgjczMQKBgEmDReLyf6qE0ywsnBETCbg8kdDAtHWGd8C2O5179tgaj+yTtV+bAIRaEQX4SWUa8xya57+CAhXwKIn3pQ3tR/KfO1B+So6d4tVEd4g9FnpJp3CdJmVN3NpwSH8iskqff9Lio00vDwTEeMfQIl/0lxIYpe8MmiByvc0pFR+eVwoxAoGAZjQ5z+ss6Rh7MocP1HtynQbDfq1XOVjfZGeXAmBpgNoC+/xWWTv/AhV8Z87hTOkfMjeIkZh1aoeup2Dyp+HXCt7P0sqNvgiMxVfxAMO0hiu05M5+uYyznpwPy7vNq6NeJTHWIosJSh/9NVAlbuJkgZz6q9DpNmjLGkZobZYjuQECgYEAphBa1ZhHviTLRWCXRTo3oEC1sZwr+ikRe5+GORYtQwSujMG2FHMT8+oKFtAyZQRkubcmBY/wBSB8GJ3iw/4sn8YTf0CRkdtPcjfWljyQHekcu8DcgX7YGy5D/p+IrFsi9gvfYEZ5JxlWAGBF60CGkQxR2xHtxp9vjvx8yvzwX14=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkLEoKZyxo0YD2wYfonUpdh65oNHdR/Mjm3kH9DrKjBnFqi+yc3EovyX7zpEHNLyVGFnAtjMACDhKp0aK3110d8UDrOl5PTuh/dq0I6WxvJOaOb2ILteaX0AgSqPN94Il0GNe1TTg0zrZ32kCYzJnTOFuSzKk/bI1vSGZ9ZEC6NVcOLL+kgwo1RAlK/g6VaImuhJUf8UgEm+mAg/DgSCvLyfxgybwSKXOAR8XoqFHH4WFGacDF2NZT3nMlOrh2JNq9Nx3CXXMu2QdrANdChZFi5MFW5FOe/cY0Nyvv1h31RRbUKslu5de68WL09gf4l2L+jl9NULqMwJl+D86MISNtQIDAQAB
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  sysServiceProviderId: 1234
  returnUrl: http://5ab30025.ngrok.io/pay/returnUrl
  notifyUrl: http://5ab30025.ngrok.io/pay/alipayNotify